use anyhow::{Result, anyhow, bail};
use std::collections::{BTreeMap, BTreeSet};
use veryl_analyzer::ir::{
    AssignDestination, Component, Declaration, Expression, Factor, Ir, Module, Op, Statement,
    VarId, VarKind, Variable,
};

pub fn emit_css(ir: &Ir) -> Result<String> {
    let modules: Vec<&Module> = ir
        .components
        .iter()
        .filter_map(|component| match component {
            Component::Module(module) => Some(module),
            _ => None,
        })
        .collect();

    if modules.len() != 1 {
        bail!("expected exactly one top module, found {}", modules.len());
    }

    let module = modules[0];
    let module_name = module.name.to_string();

    // Build a complete VarId → CSS custom property name mapping upfront.
    // Param/Const are excluded (None) since they have no CSS representation.
    let mut names = BTreeMap::<VarId, String>::new();
    let mut css_vars = BTreeSet::<String>::new();

    for (id, variable) in &module.variables {
        ensure_i32_like(variable)?;
        if let Some(css_name) = variable_css_name(variable, &module_name)? {
            names.insert(*id, css_name.clone());
            css_vars.insert(css_name);
        }
    }

    let mut body_lines = Vec::<String>::new();
    let mut saw_comb = false;

    for declaration in &module.declarations {
        match declaration {
            Declaration::Comb(comb) => {
                saw_comb = true;
                for statement in &comb.statements {
                    emit_statement(statement, &names, &mut body_lines)?;
                }
            }
            Declaration::Null => {}
            other => bail!("only combinational declarations are supported, got {other}"),
        }
    }

    if !saw_comb {
        bail!("no comb declaration found");
    }

    let mut out = String::from("/* generated by veryl-css */\n\n");
    for css_var in &css_vars {
        out.push_str(&format!(
            "@property {css_var} {{\n  syntax: \"<integer>\";\n  inherits: true;\n  initial-value: 0;\n}}\n\n"
        ));
    }
    out.push_str(":root {\n");
    for line in body_lines {
        out.push_str("  ");
        out.push_str(&line);
        out.push('\n');
    }
    out.push_str("}\n");
    Ok(out)
}

fn emit_statement(
    statement: &Statement,
    names: &BTreeMap<VarId, String>,
    out: &mut Vec<String>,
) -> Result<()> {
    match statement {
        Statement::Assign(assign) => {
            if assign.dst.len() != 1 {
                bail!("only single-destination assignments are supported");
            }
            let dst = &assign.dst[0];
            ensure_simple_dst(dst)?;
            let dst_name = names
                .get(&dst.id)
                .ok_or_else(|| anyhow!("unknown assignment destination: {}", dst.id))?;
            let expr = emit_expr(&assign.expr, names)?;
            out.push(format!("{dst_name}: {expr};"));
            Ok(())
        }
        Statement::Null => Ok(()),
        other => bail!("unsupported statement: {other}"),
    }
}

fn emit_expr(expr: &Expression, names: &BTreeMap<VarId, String>) -> Result<String> {
    match expr {
        Expression::Term(factor) => emit_factor(factor, names),
        Expression::Unary(op, inner, _) => {
            let inner = emit_expr(inner, names)?;
            match op {
                Op::Add => Ok(inner),
                Op::Sub => Ok(format!("calc(-1 * ({inner}))")),
                _ => bail!("unsupported unary operator: {op}"),
            }
        }
        Expression::Binary(lhs, op, rhs, _) => {
            let lhs = emit_expr(lhs, names)?;
            let rhs = emit_expr(rhs, names)?;
            emit_binary(op, &lhs, &rhs)
        }
        other => bail!("unsupported expression: {other}"),
    }
}

fn emit_factor(factor: &Factor, names: &BTreeMap<VarId, String>) -> Result<String> {
    match factor {
        Factor::Variable(id, index, select, _) => {
            if index.dimension() != 0 {
                bail!("array indexing is unsupported");
            }
            if !select.to_string().is_empty() {
                bail!("bit/part-select is unsupported");
            }
            let css_name = names
                .get(id)
                .ok_or_else(|| anyhow!("unknown variable id: {id}"))?;
            Ok(format!("var({css_name})"))
        }
        Factor::Value(comptime) => {
            let value = comptime
                .get_value()
                .map_err(|_| anyhow!("failed to evaluate literal value"))?;
            literal_to_css_int(&format!("{value:x}"))
        }
        other => bail!("unsupported factor: {other}"),
    }
}

fn emit_binary(op: &Op, lhs: &str, rhs: &str) -> Result<String> {
    Ok(match op {
        Op::Add => format!("calc(({lhs}) + ({rhs}))"),
        Op::Sub => format!("calc(({lhs}) - ({rhs}))"),
        Op::Mul => format!("calc(({lhs}) * ({rhs}))"),
        Op::Div => format!("round(to-zero, calc(({lhs}) / ({rhs})), 1)"),
        Op::Rem => format!("rem(({lhs}), ({rhs}))"),
        _ => bail!("unsupported binary operator: {op}"),
    })
}

/// Returns the CSS custom property name for a variable, or `None` for Param/Const
/// (which have no runtime CSS representation).
fn variable_css_name(variable: &Variable, module_name: &str) -> Result<Option<String>> {
    let signal = last_path_segment(&variable.path.to_string())?;
    Ok(match variable.kind {
        VarKind::Input | VarKind::Output | VarKind::Inout => Some(format!("--{signal}")),
        VarKind::Variable | VarKind::Let => Some(format!("--{module_name}-{signal}")),
        VarKind::Param | VarKind::Const => None,
    })
}

fn ensure_simple_dst(dst: &AssignDestination) -> Result<()> {
    if dst.index.dimension() != 0 {
        bail!("array destination is unsupported");
    }
    if !dst.select.to_string().is_empty() {
        bail!("bit/part-select destination is unsupported");
    }
    Ok(())
}

fn ensure_i32_like(variable: &Variable) -> Result<()> {
    let ty = variable.r#type.to_string();
    if ty == "signed bit<32>" {
        Ok(())
    } else {
        bail!(
            "only `signed bit<32>` variables are supported, got `{}` for `{}`",
            ty,
            variable.path
        )
    }
}

fn last_path_segment(path: &str) -> Result<String> {
    path.rsplit('.')
        .next()
        .map(|x| x.to_string())
        .ok_or_else(|| anyhow!("empty path"))
}

/// Converts a Veryl literal (as a hex string from `get_value()`) to a CSS integer string.
fn literal_to_css_int(text: &str) -> Result<String> {
    let normalized = text.trim().replace('_', "");
    let lower = normalized.to_ascii_lowercase();

    if lower.contains('x') || lower.contains('z') {
        bail!("x/z containing literal is unsupported: {text}");
    }

    if let Some((_, rhs)) = lower.split_once('\'') {
        let Some((signed_and_base, digits)) = rhs.split_at_checked(1) else {
            bail!("unsupported literal: {text}");
        };
        let (base_ch, digits) = if signed_and_base == "s" {
            let Some((base, digits)) = digits.split_at_checked(1) else {
                bail!("unsupported literal: {text}");
            };
            (base.chars().next().unwrap(), digits)
        } else {
            (signed_and_base.chars().next().unwrap(), digits)
        };
        let value = match base_ch {
            'h' => i128::from_str_radix(digits, 16)?,
            'd' => digits.parse::<i128>()?,
            'b' => i128::from_str_radix(digits, 2)?,
            'o' => i128::from_str_radix(digits, 8)?,
            _ => bail!("unsupported literal base in {text}"),
        };
        return Ok(value.to_string());
    }

    if lower.starts_with('-') || lower.chars().all(|c| c.is_ascii_digit()) {
        return Ok(lower);
    }

    bail!("unsupported literal syntax: {text}")
}
