use anyhow::{Result, anyhow, bail};
use std::collections::{BTreeMap, BTreeSet};
use veryl_analyzer::ir::{
    AssignDestination, AssignStatement, Component, Declaration, Expression, Factor,
    IfResetStatement, IfStatement, Ir, Module, Op, Statement, VarId, VarKind, Variable,
};

pub struct Output {
    pub css: String,
}

pub fn emit(ir: &Ir) -> Result<Output> {
    let modules: Vec<&Module> = ir
        .components
        .iter()
        .filter_map(|c| if let Component::Module(m) = c { Some(m) } else { None })
        .collect();
    match modules.as_slice() {
        [module] => emit_module(module),
        _ => bail!("expected exactly one top module, found {}", modules.len()),
    }
}

struct FfRegInfo {
    current: String,
    next: String,
    captured: String,
    hoist: String,
}

#[derive(Clone, Copy)]
struct TypeInfo {
    width: u32,
    signed: bool,
}

struct Ctx<'a> {
    names: &'a BTreeMap<VarId, String>,
    types: &'a BTreeMap<VarId, TypeInfo>,
    cond_counter: usize,
    used_comp_fns: BTreeSet<CompFn>,
    used_bit_fns: BTreeSet<BitFn>,
}

impl<'a> Ctx<'a> {
    fn new(names: &'a BTreeMap<VarId, String>, types: &'a BTreeMap<VarId, TypeInfo>) -> Self {
        Self {
            names,
            types,
            cond_counter: 0,
            used_comp_fns: BTreeSet::new(),
            used_bit_fns: BTreeSet::new(),
        }
    }

    fn next_cond_var(&mut self) -> String {
        let n = self.cond_counter;
        self.cond_counter += 1;
        format!("--veryl-cond-{n}")
    }
}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum CompFn { Lt, Lte, Gt, Gte, Eq, Neq }

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum BitFn { And8, And16, Or8, Or16, Xor8, Xor16, Not8, Not16, Shl8, Shl16, Shr8, Shr16 }

fn emit_module(module: &Module) -> Result<Output> {
    let module_name = module.name.to_string();

    let mut clock_ids = BTreeSet::<VarId>::new();
    let mut reset_ids = BTreeSet::<VarId>::new();
    let mut ff_assigned_ids = BTreeSet::<VarId>::new();

    for decl in &module.declarations {
        if let Declaration::Ff(ff) = decl {
            clock_ids.insert(ff.clock.id);
            if let Some(r) = &ff.reset {
                reset_ids.insert(r.id);
            }
            collect_assigned_ids(&ff.statements, &mut ff_assigned_ids);
        }
    }

    let has_ff = !clock_ids.is_empty();

    let mut names = BTreeMap::<VarId, String>::new();
    let mut types = BTreeMap::<VarId, TypeInfo>::new();
    let mut ff_regs = BTreeMap::<VarId, FfRegInfo>::new();
    let mut public_css_vars = BTreeSet::<String>::new();

    for (&id, variable) in &module.variables {
        if clock_ids.contains(&id) {
            continue;
        }
        let is_reset = reset_ids.contains(&id);
        if !is_reset {
            let ti = parse_type_info(variable)?;
            types.insert(id, ti);
        }
        let Some(css_name) = variable_css_name(variable, &module_name)? else {
            continue;
        };
        if ff_assigned_ids.contains(&id) && !is_reset {
            let signal = last_path_segment(&variable.path.to_string())?;
            let base = format!("--{module_name}-{signal}");
            ff_regs.insert(id, FfRegInfo {
                current: css_name.clone(),
                next: format!("{base}-next"),
                captured: format!("{base}-captured"),
                hoist: format!("{base}-hoist"),
            });
        }
        names.insert(id, css_name.clone());
        public_css_vars.insert(css_name);
    }

    let ff_next_names: BTreeMap<VarId, String> =
        ff_regs.iter().map(|(id, i)| (*id, i.next.clone())).collect();

    let mut ctx = Ctx::new(&names, &types);
    let mut ff_current_lines = Vec::<String>::new();
    let mut comb_lines = Vec::<String>::new();
    let mut ff_next_lines = Vec::<String>::new();
    let mut saw_comb = false;

    for info in ff_regs.values() {
        ff_current_lines.push(format!("{}: var({}, 0);", info.current, info.hoist));
    }

    for decl in &module.declarations {
        match decl {
            Declaration::Comb(comb) => {
                saw_comb = true;
                for stmt in &comb.statements {
                    emit_comb_statement(stmt, &mut ctx, &mut comb_lines)?;
                }
            }
            Declaration::Ff(ff) => {
                for stmt in &ff.statements {
                    emit_ff_statement(stmt, &mut ctx, &ff_next_names, &mut ff_next_lines)?;
                }
            }
            Declaration::Null => {}
            other => bail!("unsupported declaration: {other}"),
        }
    }

    if !has_ff && !saw_comb {
        bail!("no comb or ff declaration found");
    }

    let mut css = String::from("/* generated by veryl-css */\n\n");

    if !ctx.used_comp_fns.is_empty() {
        css.push_str(&css_comp_functions(&ctx.used_comp_fns));
    }
    if !ctx.used_bit_fns.is_empty() {
        css.push_str(&css_bit_functions(&ctx.used_bit_fns));
    }
    for n in 0..ctx.cond_counter {
        css.push_str(&css_property(&format!("--veryl-cond-{n}")));
    }
    for var in &public_css_vars {
        css.push_str(&css_property(var));
    }

    if has_ff {
        let body_lines = ff_current_lines.iter().chain(&comb_lines).chain(&ff_next_lines);
        css.push_str(&css_block("body", body_lines));

        let mut hoist_inner = Vec::<String>::new();
        let mut capture_inner = Vec::<String>::new();
        for info in ff_regs.values() {
            hoist_inner.push(format!("{}: var({}, 0);", info.hoist, info.captured));
            capture_inner.push(format!("{}: var({});", info.captured, info.next));
        }
        css.push_str(&css_keyframes("hoist", &hoist_inner));
        css.push_str(&css_keyframes("capture", &capture_inner));
    } else {
        css.push_str(&css_block(":root", &comb_lines));
    }

    Ok(Output { css })
}

fn collect_assigned_ids(statements: &[Statement], ids: &mut BTreeSet<VarId>) {
    for stmt in statements {
        match stmt {
            Statement::Assign(a) => ids.extend(a.dst.iter().map(|d| d.id)),
            Statement::If(s) => {
                collect_assigned_ids(&s.true_side, ids);
                collect_assigned_ids(&s.false_side, ids);
            }
            Statement::IfReset(s) => {
                collect_assigned_ids(&s.true_side, ids);
                collect_assigned_ids(&s.false_side, ids);
            }
            _ => {}
        }
    }
}

fn emit_ff_statement(
    statement: &Statement,
    ctx: &mut Ctx,
    ff_next_names: &BTreeMap<VarId, String>,
    out: &mut Vec<String>,
) -> Result<()> {
    match statement {
        Statement::Assign(assign) => {
            let (dst, expr) = unpack_assign_expr(assign, ctx)?;
            let next = ff_next_names
                .get(&dst.id)
                .ok_or_else(|| anyhow!("ff assignment to non-ff variable: {}", dst.id))?;
            out.push(format!("{next}: {expr};"));
            Ok(())
        }
        Statement::If(if_stmt) => {
            let mut preamble = Vec::new();
            let vals = eval_if_expr(if_stmt, ctx, &mut preamble)?;
            out.extend(preamble);
            for (id, expr) in vals {
                let next = ff_next_names
                    .get(&id)
                    .ok_or_else(|| anyhow!("if assigns to non-ff variable: {id}"))?;
                out.push(format!("{next}: {expr};"));
            }
            Ok(())
        }
        Statement::IfReset(if_reset) => emit_if_reset(if_reset, ctx, ff_next_names, out),
        Statement::Null => Ok(()),
        other => bail!("unsupported ff statement: {other}"),
    }
}

fn emit_if_reset(
    if_reset: &IfResetStatement,
    ctx: &mut Ctx,
    ff_next_names: &BTreeMap<VarId, String>,
    out: &mut Vec<String>,
) -> Result<()> {
    let mut preamble = Vec::new();
    let reset_exprs = eval_branch(&if_reset.true_side, ctx, &mut preamble)?;
    let normal_exprs = eval_branch(&if_reset.false_side, ctx, &mut preamble)?;
    out.extend(preamble);

    let all_ids: BTreeSet<VarId> =
        reset_exprs.keys().chain(normal_exprs.keys()).cloned().collect();

    for id in all_ids {
        let next = ff_next_names
            .get(&id)
            .ok_or_else(|| anyhow!("if_reset assigns to non-ff variable: {id}"))?;
        let line = match (reset_exprs.get(&id), normal_exprs.get(&id)) {
            (Some(rv), Some(nv)) => format!("{next}: if(style(--rst: 1): {rv}; else: {nv});"),
            (Some(rv), None)     => format!("{next}: {rv};"),
            (None, Some(nv))     => format!("{next}: {nv};"),
            (None, None)         => unreachable!(),
        };
        out.push(line);
    }
    Ok(())
}

fn eval_branch(
    stmts: &[Statement],
    ctx: &mut Ctx,
    preamble: &mut Vec<String>,
) -> Result<BTreeMap<VarId, String>> {
    let mut map = BTreeMap::new();
    for stmt in stmts {
        match stmt {
            Statement::Assign(a) => {
                let (dst, expr) = unpack_assign_expr(a, ctx)?;
                map.insert(dst.id, expr);
            }
            Statement::If(if_stmt) => map.extend(eval_if_expr(if_stmt, ctx, preamble)?),
            Statement::Null => {}
            other => bail!("unsupported statement in branch: {other}"),
        }
    }
    Ok(map)
}

fn eval_if_expr(
    if_stmt: &IfStatement,
    ctx: &mut Ctx,
    preamble: &mut Vec<String>,
) -> Result<BTreeMap<VarId, String>> {
    let cond_var = ctx.next_cond_var();
    let cond_str = emit_condition(&if_stmt.cond, ctx)?;
    preamble.push(format!("{cond_var}: {cond_str};"));

    let true_exprs = eval_branch(&if_stmt.true_side, ctx, preamble)?;
    let false_exprs = eval_branch(&if_stmt.false_side, ctx, preamble)?;

    let all_ids: BTreeSet<VarId> =
        true_exprs.keys().chain(false_exprs.keys()).cloned().collect();

    all_ids.into_iter().map(|id| {
        let t = true_exprs.get(&id)
            .ok_or_else(|| anyhow!("variable {id} not assigned in true branch"))?;
        let f = false_exprs.get(&id)
            .ok_or_else(|| anyhow!("variable {id} not assigned in false branch"))?;
        Ok((id, format!("if(style({cond_var}: 1): {t}; else: {f})")))
    }).collect()
}

fn emit_comb_statement(
    statement: &Statement,
    ctx: &mut Ctx,
    out: &mut Vec<String>,
) -> Result<()> {
    match statement {
        Statement::Assign(assign) => {
            let (dst, expr) = unpack_assign_expr(assign, ctx)?;
            let dst_name = ctx.names
                .get(&dst.id)
                .ok_or_else(|| anyhow!("unknown assignment destination: {}", dst.id))?;
            out.push(format!("{dst_name}: {expr};"));
            Ok(())
        }
        Statement::If(if_stmt) => {
            let mut preamble = Vec::new();
            let vals = eval_if_expr(if_stmt, ctx, &mut preamble)?;
            out.extend(preamble);
            for (id, expr) in vals {
                let dst_name = ctx.names
                    .get(&id)
                    .ok_or_else(|| anyhow!("unknown variable in if branch: {id}"))?;
                out.push(format!("{dst_name}: {expr};"));
            }
            Ok(())
        }
        Statement::Null => Ok(()),
        other => bail!("unsupported statement: {other}"),
    }
}

fn emit_condition(expr: &Expression, ctx: &mut Ctx) -> Result<String> {
    match expr {
        Expression::Unary(Op::LogicNot, inner, _) => {
            Ok(format!("calc(1 - ({}))", emit_condition(inner, ctx)?))
        }
        Expression::Binary(lhs, Op::LogicAnd, rhs, _) => {
            Ok(format!("min({}, {})", emit_condition(lhs, ctx)?, emit_condition(rhs, ctx)?))
        }
        Expression::Binary(lhs, Op::LogicOr, rhs, _) => {
            Ok(format!("max({}, {})", emit_condition(lhs, ctx)?, emit_condition(rhs, ctx)?))
        }
        Expression::Binary(lhs, op, rhs, _) => {
            let (fn_name, comp) = match op {
                Op::Less      => ("--veryl-lt",  CompFn::Lt),
                Op::LessEq    => ("--veryl-lte", CompFn::Lte),
                Op::Greater   => ("--veryl-gt",  CompFn::Gt),
                Op::GreaterEq => ("--veryl-gte", CompFn::Gte),
                Op::Eq        => ("--veryl-eq",  CompFn::Eq),
                Op::Ne        => ("--veryl-neq", CompFn::Neq),
                _ => bail!("unsupported condition operator: {op}"),
            };
            ctx.used_comp_fns.insert(comp);
            let (lhs_css, _) = emit_expr(lhs, ctx)?;
            let (rhs_css, _) = emit_expr(rhs, ctx)?;
            Ok(format!("{fn_name}({lhs_css}, {rhs_css})"))
        }
        other => bail!("unsupported condition expression: {other}"),
    }
}

fn emit_expr(expr: &Expression, ctx: &mut Ctx) -> Result<(String, Option<TypeInfo>)> {
    match expr {
        Expression::Term(factor) => emit_factor(factor, ctx),
        Expression::Unary(op, inner, _) => {
            let (inner_css, inner_type) = emit_expr(inner, ctx)?;
            match op {
                Op::Add => Ok((inner_css, inner_type)),
                Op::Sub => Ok((format!("calc(-1 * ({inner_css}))"), inner_type)),
                Op::BitNot => {
                    let ti = inner_type
                        .ok_or_else(|| anyhow!("cannot determine type width for bitwise NOT"))?;
                    if ti.signed {
                        bail!("bitwise NOT is only supported for unsigned types (u8, u16)");
                    }
                    let (fn_name, bit_fn) = match ti.width {
                        8  => ("--veryl-bnot8",  BitFn::Not8),
                        16 => ("--veryl-bnot16", BitFn::Not16),
                        w  => bail!("bitwise NOT unsupported for {w}-bit type"),
                    };
                    ctx.used_bit_fns.insert(bit_fn);
                    Ok((format!("{fn_name}({inner_css})"), Some(ti)))
                }
                _ => bail!("unsupported unary operator: {op}"),
            }
        }
        Expression::Binary(lhs, op, rhs, _) => {
            let (lhs_css, lhs_type) = emit_expr(lhs, ctx)?;
            let (rhs_css, rhs_type) = emit_expr(rhs, ctx)?;
            let result_type = lhs_type.or(rhs_type);
            match op {
                Op::BitAnd | Op::BitOr | Op::BitXor => {
                    let ti = result_type
                        .ok_or_else(|| anyhow!("cannot determine type width for bitwise op"))?;
                    if ti.signed {
                        bail!("bitwise AND/OR/XOR is only supported for unsigned types (u8, u16)");
                    }
                    let (fn_name, bit_fn) = match (op, ti.width) {
                        (Op::BitAnd, 8)  => ("--veryl-band8",  BitFn::And8),
                        (Op::BitAnd, 16) => ("--veryl-band16", BitFn::And16),
                        (Op::BitOr,  8)  => ("--veryl-bor8",   BitFn::Or8),
                        (Op::BitOr,  16) => ("--veryl-bor16",  BitFn::Or16),
                        (Op::BitXor, 8)  => ("--veryl-bxor8",  BitFn::Xor8),
                        (Op::BitXor, 16) => ("--veryl-bxor16", BitFn::Xor16),
                        (_, w) => bail!("bitwise op unsupported for {w}-bit type"),
                    };
                    ctx.used_bit_fns.insert(bit_fn);
                    Ok((format!("{fn_name}({lhs_css}, {rhs_css})"), Some(ti)))
                }
                Op::LogicShiftL | Op::LogicShiftR => {
                    let ti = result_type
                        .ok_or_else(|| anyhow!("cannot determine type width for shift"))?;
                    if ti.signed {
                        bail!("logical shifts are only supported for unsigned types (u8, u16)");
                    }
                    let (fn_name, bit_fn) = match (op, ti.width) {
                        (Op::LogicShiftL, 8)  => ("--veryl-bshl8",  BitFn::Shl8),
                        (Op::LogicShiftL, 16) => ("--veryl-bshl16", BitFn::Shl16),
                        (Op::LogicShiftR, 8)  => ("--veryl-bshr8",  BitFn::Shr8),
                        (Op::LogicShiftR, 16) => ("--veryl-bshr16", BitFn::Shr16),
                        (_, w) => bail!("shift unsupported for {w}-bit type"),
                    };
                    ctx.used_bit_fns.insert(bit_fn);
                    Ok((format!("{fn_name}({lhs_css}, {rhs_css})"), Some(ti)))
                }
                _ => {
                    let css = emit_binary(op, &lhs_css, &rhs_css)?;
                    Ok((css, result_type))
                }
            }
        }
        other => bail!("unsupported expression: {other}"),
    }
}

fn emit_factor(factor: &Factor, ctx: &mut Ctx) -> Result<(String, Option<TypeInfo>)> {
    match factor {
        Factor::Variable(id, index, select, _) => {
            if index.dimension() != 0 {
                bail!("array indexing is unsupported");
            }
            if !select.to_string().is_empty() {
                bail!("bit/part-select is unsupported");
            }
            let css_name = ctx.names
                .get(id)
                .ok_or_else(|| anyhow!("unknown variable id: {id}"))?;
            let ti = ctx.types.get(id).copied();
            Ok((format!("var({css_name})"), ti))
        }
        Factor::Value(comptime) => {
            let value = comptime
                .get_value()
                .map_err(|_| anyhow!("failed to evaluate literal value"))?;
            // LowerHex on Value produces Veryl literal format e.g. "32'sh00000001"
            let css = literal_to_css_int(&format!("{value:x}"))?;
            Ok((css, None))
        }
        other => bail!("unsupported factor: {other}"),
    }
}

fn emit_binary(op: &Op, lhs: &str, rhs: &str) -> Result<String> {
    Ok(match op {
        Op::Add => format!("calc(({lhs}) + ({rhs}))"),
        Op::Sub => format!("calc(({lhs}) - ({rhs}))"),
        Op::Mul => format!("calc(({lhs}) * ({rhs}))"),
        Op::Div => format!("round(to-zero, calc(({lhs}) / ({rhs})), 1)"),
        Op::Rem => format!("rem(({lhs}), ({rhs}))"),
        _ => bail!("unsupported binary operator: {op}"),
    })
}

fn unpack_assign_expr<'a>(
    assign: &'a AssignStatement,
    ctx: &mut Ctx,
) -> Result<(&'a AssignDestination, String)> {
    if assign.dst.len() != 1 {
        bail!("only single-destination assignments are supported");
    }
    let dst = &assign.dst[0];
    if dst.index.dimension() != 0 {
        bail!("array destination is unsupported");
    }
    if !dst.select.to_string().is_empty() {
        bail!("bit/part-select destination is unsupported");
    }
    let (css, _) = emit_expr(&assign.expr, ctx)?;
    Ok((dst, css))
}

fn css_comp_functions(used: &BTreeSet<CompFn>) -> String {
    let all: &[(CompFn, &str, &str)] = &[
        (CompFn::Lt,  "--veryl-lt",  "clamp(0, sign(calc(var(--b) - var(--a))), 1)"),
        (CompFn::Lte, "--veryl-lte", "clamp(0, calc(1 + sign(calc(var(--b) - var(--a)))), 1)"),
        (CompFn::Gt,  "--veryl-gt",  "clamp(0, sign(calc(var(--a) - var(--b))), 1)"),
        (CompFn::Gte, "--veryl-gte", "clamp(0, calc(1 + sign(calc(var(--a) - var(--b)))), 1)"),
        (CompFn::Eq,  "--veryl-eq",  "clamp(0, calc(1 - abs(sign(calc(var(--a) - var(--b))))), 1)"),
        (CompFn::Neq, "--veryl-neq", "abs(sign(calc(var(--a) - var(--b))))"),
    ];
    let mut s = String::new();
    for (tag, name, body) in all {
        if used.contains(tag) {
            s.push_str(&format!(
                "@function {name}(--a <number>, --b <number>) returns <integer> {{\n  result: {body};\n}}\n\n"
            ));
        }
    }
    s
}

fn css_bit_functions(used: &BTreeSet<BitFn>) -> String {
    let all: &[(BitFn, u32, &str)] = &[
        (BitFn::And8,  8,  "and"),
        (BitFn::And16, 16, "and"),
        (BitFn::Or8,   8,  "or"),
        (BitFn::Or16,  16, "or"),
        (BitFn::Xor8,  8,  "xor"),
        (BitFn::Xor16, 16, "xor"),
        (BitFn::Not8,  8,  "not"),
        (BitFn::Not16, 16, "not"),
        (BitFn::Shl8,  8,  "shl"),
        (BitFn::Shl16, 16, "shl"),
        (BitFn::Shr8,  8,  "shr"),
        (BitFn::Shr16, 16, "shr"),
    ];
    let mut s = String::new();
    for &(tag, bits, op) in all {
        if used.contains(&tag) {
            s.push_str(&css_bit_function_body(bits, op));
        }
    }
    s
}

fn css_bit_function_body(bits: u32, op: &str) -> String {
    let suffix = bits;
    match op {
        "not" => {
            let max_val = (1u64 << bits) - 1;
            format!(
                "@function --veryl-bnot{suffix}(--a <integer>) returns <integer> {{\n  result: calc({max_val} - var(--a));\n}}\n\n"
            )
        }
        "shr" => {
            format!(
                "@function --veryl-bshr{suffix}(--a <integer>, --b <integer>) returns <integer> {{\n  result: round(down, var(--a) / pow(2, var(--b)));\n}}\n\n"
            )
        }
        "shl" => {
            let entries: String = (0..bits)
                .map(|i| format!("style(--b:{}):{}; ", i, 1u64 << i))
                .collect();
            let max_val = 1u64 << bits;
            format!(
                "@function --veryl-bshl{suffix}(--a <integer>, --b <integer>) returns <integer> {{\n  --shift: if({entries}else:1);\n  result: mod(calc(var(--a) * var(--shift)), {max_val});\n}}\n\n"
            )
        }
        _ => {
            // "and", "or", "xor": bit decomposition
            let mut body = String::new();
            for i in 0..bits {
                let extract = if i == 0 {
                    "mod(var(--a), 2)".to_string()
                } else {
                    format!("mod(round(down, var(--a) / {}), 2)", 1u64 << i)
                };
                body.push_str(&format!("  --a{}: {extract};\n", i + 1));
            }
            for i in 0..bits {
                let extract = if i == 0 {
                    "mod(var(--b), 2)".to_string()
                } else {
                    format!("mod(round(down, var(--b) / {}), 2)", 1u64 << i)
                };
                body.push_str(&format!("  --b{}: {extract};\n", i + 1));
            }
            let terms: Vec<String> = (0..bits).map(|i| {
                let j = i + 1;
                let coeff = 1u64 << i;
                let bit_expr = match op {
                    "and" => format!("var(--a{j}) * var(--b{j})"),
                    "or"  => format!("min(1, calc(var(--a{j}) + var(--b{j})))"),
                    "xor" => format!("calc(min(1, calc(var(--a{j}) + var(--b{j}))) - var(--a{j}) * var(--b{j}))"),
                    _ => unreachable!(),
                };
                if i == 0 { bit_expr } else { format!("{bit_expr} * {coeff}") }
            }).collect();
            body.push_str("  result: calc(\n");
            for (idx, term) in terms.iter().enumerate() {
                let sep = if idx < terms.len() - 1 { " +" } else { "" };
                body.push_str(&format!("    {term}{sep}\n"));
            }
            body.push_str("  );\n");
            format!("@function --veryl-b{op}{suffix}(--a <integer>, --b <integer>) returns <integer> {{\n{body}}}\n\n")
        }
    }
}

fn css_property(var: &str) -> String {
    format!(
        "@property {var} {{\n  syntax: \"<integer>\";\n  inherits: true;\n  initial-value: 0;\n}}\n\n"
    )
}

fn css_block<'a>(selector: &str, lines: impl IntoIterator<Item = &'a String>) -> String {
    let mut s = format!("{selector} {{\n");
    for line in lines {
        s.push_str(&format!("  {line}\n"));
    }
    s.push_str("}\n\n");
    s
}

fn css_keyframes(name: &str, lines: &[String]) -> String {
    let inner = lines.iter().map(|l| format!("    {l}")).collect::<Vec<_>>().join("\n");
    format!("@keyframes {name} {{\n  0%, 100% {{\n{inner}\n  }}\n}}\n\n")
}

fn variable_css_name(variable: &Variable, module_name: &str) -> Result<Option<String>> {
    let signal = last_path_segment(&variable.path.to_string())?;
    Ok(match variable.kind {
        VarKind::Input | VarKind::Output | VarKind::Inout => Some(format!("--{signal}")),
        VarKind::Variable | VarKind::Let => Some(format!("--{module_name}-{signal}")),
        VarKind::Param | VarKind::Const => None,
    })
}

fn parse_type_info(variable: &Variable) -> Result<TypeInfo> {
    let ty = variable.r#type.to_string();
    match ty.as_str() {
        "signed bit<8>"  => Ok(TypeInfo { width: 8,  signed: true }),
        "signed bit<16>" => Ok(TypeInfo { width: 16, signed: true }),
        "signed bit<32>" => Ok(TypeInfo { width: 32, signed: true }),
        "bit<8>"         => Ok(TypeInfo { width: 8,  signed: false }),
        "bit<16>"        => Ok(TypeInfo { width: 16, signed: false }),
        _ => bail!(
            "unsupported type `{}` for `{}`; supported: i8, i16, i32, u8, u16",
            ty,
            variable.path
        ),
    }
}

fn last_path_segment(path: &str) -> Result<String> {
    path.rsplit('.').next().map(|s| s.to_string()).ok_or_else(|| anyhow!("empty path"))
}

// Parse a Veryl literal (e.g. "32'sh00000001") or plain decimal into a CSS integer string.
fn literal_to_css_int(text: &str) -> Result<String> {
    let normalized = text.trim().replace('_', "").to_ascii_lowercase();

    if normalized.contains('x') || normalized.contains('z') {
        bail!("x/z literal is unsupported: {text}");
    }

    if let Some((width_str, rhs)) = normalized.split_once('\'') {
        let signed = rhs.starts_with('s');
        let rest = if signed { &rhs[1..] } else { rhs };
        let (base_ch, digits) = rest.split_at(1);
        let width: Option<u32> = width_str.parse().ok();

        let unsigned_val: u128 = match base_ch {
            "h" => u128::from_str_radix(digits, 16)?,
            "d" => digits.parse()?,
            "b" => u128::from_str_radix(digits, 2)?,
            "o" => u128::from_str_radix(digits, 8)?,
            _ => bail!("unsupported literal base in: {text}"),
        };

        let value: i128 = if signed {
            if let Some(w) = width.filter(|&w| w > 0 && w <= 128) {
                if (unsigned_val >> (w - 1)) & 1 == 1 {
                    (unsigned_val | (u128::MAX << w)) as i128
                } else {
                    unsigned_val as i128
                }
            } else {
                unsigned_val as i128
            }
        } else {
            unsigned_val as i128
        };

        return Ok(value.to_string());
    }

    if normalized.starts_with('-') || normalized.chars().all(|c| c.is_ascii_digit()) {
        return Ok(normalized);
    }

    bail!("unsupported literal syntax: {text}")
}
