use anyhow::{Context as _, Result, anyhow, bail};
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use veryl_analyzer::ir::{
    Component, Declaration, Expression, Factor, Ir, Module, Op, Statement, VarId, VarKind,
};
use veryl_analyzer::{Analyzer, Context};
use veryl_metadata::Metadata;
use veryl_parser::Parser;

fn main() -> Result<()> {
    let input = env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("example.veryl"));

    let code = fs::read_to_string(&input)
        .with_context(|| format!("failed to read {}", input.display()))?;

    let metadata = Metadata::create_default("prj")?;
    let parser = Parser::parse(&code, &input.display().to_string())
        .map_err(|e| anyhow!("parse error: {e:?}"))?;

    let analyzer = Analyzer::new(&metadata);
    let mut context = Context::default();
    let mut ir = Ir::default();

    let mut errors = vec![];
    errors.extend(analyzer.analyze_pass1("prj", &parser.veryl));
    errors.extend(Analyzer::analyze_post_pass1());
    errors.extend(analyzer.analyze_pass2("prj", &parser.veryl, &mut context, Some(&mut ir)));
    errors.extend(Analyzer::analyze_post_pass2());

    if !errors.is_empty() {
        eprintln!("analyzer errors:");
        for error in &errors {
            eprintln!("  {error:?}");
        }
    }

    let css = emit_css(&ir)?;
    let out_path = output_path(&input);
    fs::write(&out_path, css).with_context(|| format!("failed to write {}", out_path.display()))?;

    eprintln!("wrote {}", out_path.display());
    Ok(())
}

fn output_path(input: &Path) -> PathBuf {
    input.with_file_name("output.css")
}

fn emit_css(ir: &Ir) -> Result<String> {
    let modules: Vec<&Module> = ir
        .components
        .iter()
        .filter_map(|component| match component {
            Component::Module(module) => Some(module),
            _ => None,
        })
        .collect();

    if modules.len() != 1 {
        bail!("expected exactly one top module, found {}", modules.len());
    }

    let module = modules[0];
    let module_name = module.name.to_string();

    let mut names = BTreeMap::<VarId, String>::new();
    let mut css_vars = BTreeSet::<String>::new();

    for (id, variable) in &module.variables {
        ensure_i32_like(variable)?;

        let signal = last_path_segment(&variable.path.to_string())?;
        let css_name = match variable.kind {
            VarKind::Input | VarKind::Output | VarKind::Inout => format!("--{signal}"),
            VarKind::Variable | VarKind::Let => format!("--{module_name}-{signal}"),
            VarKind::Param | VarKind::Const => continue,
        };

        names.insert(*id, css_name.clone());
        css_vars.insert(css_name);
    }

    let mut body_lines = Vec::<String>::new();
    let mut saw_comb = false;

    for declaration in &module.declarations {
        match declaration {
            Declaration::Comb(comb) => {
                saw_comb = true;
                for statement in &comb.statements {
                    emit_statement(statement, module, &names, &mut body_lines)?;
                }
            }
            Declaration::Null => {}
            other => {
                bail!("only combinational declarations are supported, got {other}")
            }
        }
    }

    if !saw_comb {
        bail!("no comb declaration found");
    }

    let mut out = String::new();
    out.push_str("/* generated by veryl-css */\n\n");

    for css_var in &css_vars {
        out.push_str(&format!(
            "@property {css_var} {{\n  syntax: \"<integer>\";\n  inherits: true;\n  initial-value: 0;\n}}\n\n"
        ));
    }

    out.push_str(":root {\n");
    for line in body_lines {
        out.push_str("  ");
        out.push_str(&line);
        out.push('\n');
    }
    out.push_str("}\n");
    Ok(out)
}

fn emit_statement(
    statement: &Statement,
    module: &Module,
    names: &BTreeMap<VarId, String>,
    out: &mut Vec<String>,
) -> Result<()> {
    match statement {
        Statement::Assign(assign) => {
            if assign.dst.len() != 1 {
                bail!("only single-destination assignments are supported");
            }
            let dst = &assign.dst[0];
            ensure_simple_dst(dst)?;
            let dst_name = names
                .get(&dst.id)
                .cloned()
                .or_else(|| lookup_css_name(module, names, dst.id).ok())
                .ok_or_else(|| anyhow!("unknown assignment destination id: {}", dst.id))?;
            let expr = emit_expr(&assign.expr, module, names)?;
            out.push(format!("{dst_name}: {expr};"));
            Ok(())
        }
        Statement::Null => Ok(()),
        other => bail!("unsupported statement: {other}"),
    }
}

fn emit_expr(
    expr: &Expression,
    module: &Module,
    names: &BTreeMap<VarId, String>,
) -> Result<String> {
    match expr {
        Expression::Term(factor) => emit_factor(factor, module, names),
        Expression::Unary(op, inner, _) => {
            let inner = emit_expr(inner, module, names)?;
            match op {
                Op::Add => Ok(inner),
                Op::Sub => Ok(format!("calc(-1 * ({inner})")),
                _ => bail!("unsupported unary operator: {op}"),
            }
        }
        Expression::Binary(lhs, op, rhs, _) => {
            let lhs = emit_expr(lhs, module, names)?;
            let rhs = emit_expr(rhs, module, names)?;
            emit_binary(op, &lhs, &rhs)
        }
        other => bail!("unsupported expression: {other}"),
    }
}

fn emit_factor(
    factor: &Factor,
    module: &Module,
    names: &BTreeMap<VarId, String>,
) -> Result<String> {
    match factor {
        Factor::Variable(id, index, select, _) => {
            if index.dimension() != 0 {
                bail!("array indexing is unsupported");
            }
            if !select.to_string().is_empty() {
                bail!("bit/part-select is unsupported");
            }
            let css_name = names
                .get(id)
                .cloned()
                .or_else(|| lookup_css_name(module, names, *id).ok())
                .ok_or_else(|| anyhow!("unknown variable id: {id}"))?;
            Ok(format!("var({css_name})"))
        }
        Factor::Value(comptime) => {
            let value = comptime
                .get_value()
                .map_err(|_| anyhow!("failed to evaluate literal value"))?;
            literal_to_css_int(&format!("{value:x}"))
        }
        other => bail!("unsupported factor: {other}"),
    }
}

fn emit_binary(op: &Op, lhs: &str, rhs: &str) -> Result<String> {
    let expr = match op {
        Op::Add => format!("calc(({lhs}) + ({rhs}))"),
        Op::Sub => format!("calc(({lhs}) - ({rhs}))"),
        Op::Mul => format!("calc(({lhs}) * ({rhs}))"),
        Op::Div => format!("round(to-zero, calc(({lhs}) / ({rhs})), 1)"),
        Op::Rem => format!("rem(({lhs}), ({rhs}))"),
        _ => bail!("unsupported binary operator: {op}"),
    };
    Ok(expr)
}

fn ensure_simple_dst(dst: &veryl_analyzer::ir::AssignDestination) -> Result<()> {
    if dst.index.dimension() != 0 {
        bail!("array destination is unsupported");
    }
    if !dst.select.to_string().is_empty() {
        bail!("bit/part-select destination is unsupported");
    }
    Ok(())
}

fn ensure_i32_like(variable: &veryl_analyzer::ir::Variable) -> Result<()> {
    let ty = variable.r#type.to_string();
    if ty == "signed bit<32>" {
        Ok(())
    } else {
        bail!(
            "only `signed bit<32>` variables are supported, got `{}` for `{}`",
            ty,
            variable.path
        )
    }
}

fn lookup_css_name(module: &Module, names: &BTreeMap<VarId, String>, id: VarId) -> Result<String> {
    if let Some(name) = names.get(&id) {
        return Ok(name.clone());
    }
    let variable = module
        .variables
        .get(&id)
        .ok_or_else(|| anyhow!("unknown variable id: {id}"))?;
    let signal = last_path_segment(&variable.path.to_string())?;
    let module_name = module.name.to_string();
    Ok(match variable.kind {
        VarKind::Input | VarKind::Output | VarKind::Inout => format!("--{signal}"),
        VarKind::Variable | VarKind::Let => format!("--{module_name}-{signal}"),
        VarKind::Param | VarKind::Const => format!("--{module_name}-{signal}"),
    })
}

fn last_path_segment(path: &str) -> Result<String> {
    path.rsplit('.')
        .next()
        .map(|x| x.to_string())
        .ok_or_else(|| anyhow!("empty path"))
}

fn literal_to_css_int(text: &str) -> Result<String> {
    let normalized = text.trim().replace('_', "");
    let lower = normalized.to_ascii_lowercase();

    if lower.contains('x') || lower.contains('z') {
        bail!("x/z containing literal is unsupported: {text}");
    }

    if let Some((_, rhs)) = lower.split_once("'") {
        let Some((signed_and_base, digits)) = rhs.split_at_checked(1) else {
            bail!("unsupported literal: {text}");
        };

        let (base_ch, digits) = if signed_and_base == "s" {
            let Some((base, digits)) = digits.split_at_checked(1) else {
                bail!("unsupported literal: {text}");
            };
            (base.chars().next().unwrap(), digits)
        } else {
            (signed_and_base.chars().next().unwrap(), digits)
        };

        let value = match base_ch {
            'h' => i128::from_str_radix(digits, 16)?,
            'd' => digits.parse::<i128>()?,
            'b' => i128::from_str_radix(digits, 2)?,
            'o' => i128::from_str_radix(digits, 8)?,
            _ => bail!("unsupported literal base in {text}"),
        };
        return Ok(value.to_string());
    }

    if lower.starts_with('-') || lower.chars().all(|c| c.is_ascii_digit()) {
        return Ok(lower);
    }

    bail!("unsupported literal syntax: {text}")
}
